# Generated by Django 3.1.4 on 2020-12-17 08:50

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.CharField(max_length=30)),
                ('employer_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phone_field.models.PhoneField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=30)),
                ('status_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_id', models.CharField(max_length=30)),
                ('job_post_name', models.CharField(max_length=30)),
                ('created_date', models.CharField(max_length=30)),
                ('job_description', models.CharField(max_length=200)),
                ('job_requirement', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=30)),
                ('is_active', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=30)),
                ('apply_date', models.DateField()),
                ('job_application_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_id', models.CharField(max_length=30)),
                ('job_post_id', models.CharField(max_length=30)),
                ('skill_set_name', models.CharField(max_length=30)),
                ('skill_level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('phone_number', phone_field.models.PhoneField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('other_staff_details', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Interview_Outcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_outcome_id', models.CharField(max_length=30)),
                ('interview_outcome_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_interview_id', models.CharField(max_length=30)),
                ('student_interview_outcome', models.CharField(max_length=30)),
                ('interview_datetime', models.DateField()),
                ('comment_by_organisation', models.CharField(max_length=30)),
                ('other_interview_details', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_start_date', models.DateField()),
                ('placement_manager_staffid', models.CharField(max_length=30)),
                ('placement_end_date', models.DateField()),
                ('comments_by_organization', models.CharField(max_length=30)),
                ('comments_by_student', models.CharField(max_length=30)),
                ('other_placement_details', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlacementAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=30)),
                ('assignment_start_date', models.DateField()),
                ('assignment_end_date', models.DateField()),
                ('comments_by_supervisor', models.CharField(max_length=30)),
                ('comments_by_student', models.CharField(max_length=30)),
                ('other_assignment_details', models.CharField(max_length=30)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
        ),
    ]
