# Generated by Django 3.1.4 on 2021-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20201218_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_interview_outcome',
            name='interview_outcome_description',
        ),
        migrations.AddField(
            model_name='student_interview_outcome',
            name='interview_outcome',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=30),
        ),
    ]
