# Generated by Django 3.1.4 on 2020-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20201217_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='created_date',
            field=models.DateField(),
        ),
    ]
