# Generated by Django 3.1.4 on 2021-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20210116_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinterview',
            name='student_interview_outcome',
        ),
        migrations.AddField(
            model_name='studentinterview',
            name='interview_outcome',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=30),
        ),
        migrations.DeleteModel(
            name='Student_Interview_Outcome',
        ),
    ]
