# Generated by Django 3.1.4 on 2021-01-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_auto_20210116_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterview',
            name='job_post_id',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='employer.jobpost'),
            preserve_default=False,
        ),
    ]
