# Generated by Django 3.1.4 on 2020-12-17 08:50

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('is_current_job', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=30)),
                ('skill_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('confirm_password', models.CharField(blank=True, max_length=250)),
                ('student_id', models.CharField(max_length=6, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('contact_number', phone_field.models.PhoneField(max_length=100)),
                ('resume', models.FileField(blank=True, upload_to=student.models.content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('skill_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('DIPLOMA', 'diploma'), ('BACHELORS', 'bachelors'), ('MASTERS', 'masters'), ('PHD', 'philospher')], default='BACHELORS', max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('institution_name', models.CharField(max_length=30)),
                ('starting_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.course')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='y1', help_text='enter username ex:y16it***', max_length=9)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('job_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobpost')),
            ],
        ),
    ]
