# Generated by Django 3.1.4 on 2021-01-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='student_id',
            field=models.CharField(max_length=30),
        ),
    ]
