# Generated by Django 3.1.4 on 2020-12-17 19:56

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_type',
            field=models.CharField(choices=[('DIPLOMA', 'Diploma'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'Philospher')], default='BACHELORS', max_length=30),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
