# Generated by Django 3.1.4 on 2021-01-22 09:39

from django.db import migrations, models
import django.db.models.deletion
import institution.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30)),
                ('event_title', models.CharField(max_length=30)),
                ('event_description', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
                ('organised_by', models.CharField(max_length=30)),
                ('event_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=30)),
                ('institution_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('phone_number', phone_field.models.PhoneField(max_length=30)),
                ('logo', models.ImageField(blank=True, upload_to=institution.models.content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', phone_field.models.PhoneField(max_length=30)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.event')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
        ),
    ]
