# Generated by Django 3.1.4 on 2021-01-20 12:44

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20201218_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', phone_field.models.PhoneField(max_length=30)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.event')),
            ],
        ),
        migrations.RemoveField(
            model_name='studenteventattendee',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='studenteventattendee',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='EmployerEventAttendee',
        ),
        migrations.DeleteModel(
            name='StudentEventAttendee',
        ),
    ]
